name: Check Variable

on:
  push:
    branches:
      - staging
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run check_variable.py
        env:
          KEY_GOIANA: ${{ secrets.KEY_GOIANA }}
        run: python src/data/nfg_scrape.py